// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFREavGK0FOGD4Q2ckS5GVTVXPs6iahc',
    appId: '1:598145394712:web:your-web-app-id',
    messagingSenderId: '598145394712',
    projectId: 'apparel-slemn24',
    authDomain: 'apparel-slemn24.firebaseapp.com',
    storageBucket: 'apparel-slemn24.firebasestorage.app',
    databaseURL: 'https://apparel-slemn24-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADFREavGK0FOGD4Q2ckS5GVTVXPs6iahc',
    appId: '1:598145394712:android:0abc024f47278dc5bffb6d',
    messagingSenderId: '598145394712',
    projectId: 'apparel-slemn24',
    storageBucket: 'apparel-slemn24.firebasestorage.app',
    databaseURL: 'https://apparel-slemn24-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADFREavGK0FOGD4Q2ckS5GVTVXPs6iahc',
    appId: '1:598145394712:ios:your-ios-app-id',
    messagingSenderId: '598145394712',
    projectId: 'apparel-slemn24',
    storageBucket: 'apparel-slemn24.firebasestorage.app',
    iosBundleId: 'com.example.flutter_project',
    databaseURL: 'https://apparel-slemn24-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADFREavGK0FOGD4Q2ckS5GVTVXPs6iahc',
    appId: '1:598145394712:ios:your-macos-app-id',
    messagingSenderId: '598145394712',
    projectId: 'apparel-slemn24',
    storageBucket: 'apparel-slemn24.firebasestorage.app',
    iosBundleId: 'com.example.flutter_project',
    databaseURL: 'https://apparel-slemn24-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADFREavGK0FOGD4Q2ckS5GVTVXPs6iahc',
    appId: '1:598145394712:web:your-windows-app-id',
    messagingSenderId: '598145394712',
    projectId: 'apparel-slemn24',
    authDomain: 'apparel-slemn24.firebaseapp.com',
    storageBucket: 'apparel-slemn24.firebasestorage.app',
    databaseURL: 'https://apparel-slemn24-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
